# Welcome to Jekyll!
#

# Site settings
title: TKVTV
description: |
  Another fine responsive  
  site template freebie  
  crafted by [HTML5 UP](http://html5up.net)
owner: Takagotch # or company name
first_published: 2020 # if migrating another site, the year of your first publish
email: your-email@domain.com
baseurl: "/page99" # the subpath of your site, e.g. /blog
url: "https://takagotch.github.io" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/
  github: https://github.com/takagotch
  linkedin-square: https://linkedin.com/in/takagotch
  facebook-official: https://facebook.com/takagotch
  google-plus-square: https://plus.google.com/u/0/takagotch
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
